# Generated by Django 5.0.2 on 2024-02-23 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mock_invest", "0001_initial"),
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinvestaccount",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament",
            ),
        ),
    ]
