# Generated by Django 5.0.2 on 2024-02-19 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockCodeModel",
            fields=[
                ("standard_code", models.CharField(default="", max_length=50)),
                (
                    "code",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("stock_name", models.CharField(default="", max_length=100)),
                ("en_name", models.CharField(default="", max_length=100)),
                ("stock_open_date", models.DateField()),
                ("market", models.CharField(default="", max_length=50)),
                ("stock_kind", models.CharField(default="", max_length=30)),
                ("affiliated", models.CharField(default="", max_length=30)),
                ("stock_type", models.CharField(default="", max_length=30)),
                ("face_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_stock_count",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockPriceRealtimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="StockInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tr_id", models.CharField(default="", max_length=100)),
                ("rt_cd", models.CharField(default="", max_length=2)),
                ("msg_cd", models.CharField(default="", max_length=20)),
                ("msg1", models.CharField(default="", max_length=150)),
                ("pdno", models.CharField(default="", max_length=100)),
                ("prdt_type_cd", models.CharField(default="", max_length=20)),
                ("mket_id_cd", models.CharField(default="", max_length=20)),
                ("scty_grp_id_cd", models.CharField(default="", max_length=20)),
                ("excg_dvsn_cd", models.CharField(default="", max_length=20)),
                ("setl_mmdd", models.CharField(default="", max_length=10)),
                ("lstg_stqt", models.CharField(default="", max_length=50)),
                ("lstg_cptl_amt", models.CharField(default="", max_length=50)),
                ("cpta", models.CharField(default="", max_length=50)),
                ("papr", models.CharField(default="", max_length=50)),
                ("issu_pric", models.CharField(default="", max_length=50)),
                ("kospi200_item_yn", models.CharField(default="", max_length=50)),
                ("scts_mket_lstg_dt", models.CharField(default="", max_length=50)),
                ("scts_mket_lstg_abol_dt", models.CharField(default="", max_length=50)),
                ("kosdap_mket_lstg_dt", models.CharField(default="", max_length=50)),
                (
                    "kosdap_mket_lstg_abol_dt",
                    models.CharField(default="", max_length=50),
                ),
                ("frbd_mket_lstg_dt", models.CharField(default="", max_length=50)),
                ("frbd_mket_lstg_abol_dt", models.CharField(default="", max_length=50)),
                ("reits_kind_cd", models.CharField(default="", max_length=50)),
                ("etf_dvsn_cd", models.CharField(default="", max_length=50)),
                ("oilf_find_yn", models.CharField(default="", max_length=50)),
                ("idx_bztp_lcls_cd", models.CharField(default="", max_length=50)),
                ("idx_bztp_mcls_cd", models.CharField(default="", max_length=50)),
                ("idx_bztp_scls_cd", models.CharField(default="", max_length=50)),
                ("stck_kind_cd", models.CharField(default="", max_length=50)),
                ("mfnd_opng_dt", models.CharField(default="", max_length=50)),
                ("mfnd_end_dt", models.CharField(default="", max_length=50)),
                ("dpsi_erlm_cncl_dt", models.CharField(default="", max_length=50)),
                ("etf_cu_qty", models.CharField(default="", max_length=50)),
                ("prdt_name", models.CharField(default="", max_length=100)),
                ("prdt_name120", models.CharField(default="", max_length=300)),
                ("prdt_abrv_name", models.CharField(default="", max_length=200)),
                ("std_pdno", models.CharField(default="", max_length=50)),
                ("prdt_eng_name", models.CharField(default="", max_length=100)),
                ("prdt_eng_name120", models.CharField(default="", max_length=300)),
                ("prdt_eng_abrv_name", models.CharField(default="", max_length=100)),
                ("dpsi_aptm_erlm_yn", models.CharField(default="", max_length=10)),
                ("etf_txtn_type_cd", models.CharField(default="", max_length=100)),
                ("etf_type_cd", models.CharField(default="", max_length=100)),
                ("lstg_abol_dt", models.CharField(default="", max_length=10)),
                ("nwst_odst_dvsn_cd", models.CharField(default="", max_length=100)),
                ("sbst_pric", models.CharField(default="", max_length=100)),
                ("thco_sbst_pric", models.CharField(default="", max_length=100)),
                (
                    "thco_sbst_pric_chng_dt",
                    models.CharField(default="", max_length=100),
                ),
                ("tr_stop_yn", models.CharField(default="", max_length=100)),
                ("admin_item_yn", models.CharField(default="", max_length=100)),
                ("thdt_clpr", models.CharField(default="", max_length=100)),
                ("bfdy_clpr", models.CharField(default="", max_length=100)),
                ("clpr_chng_dt", models.CharField(default="", max_length=100)),
                ("std_idst_clsf_cd", models.CharField(default="", max_length=100)),
                ("std_idst_clsf_cd_name", models.CharField(default="", max_length=300)),
                ("idx_bztp_lcls_cd_name", models.CharField(default="", max_length=200)),
                ("idx_bztp_mcls_cd_name", models.CharField(default="", max_length=200)),
                ("idx_bztp_scls_cd_name", models.CharField(default="", max_length=200)),
                ("ocr_no", models.CharField(default="", max_length=10)),
                ("crfd_item_yn", models.CharField(default="", max_length=10)),
                ("elec_scty_yn", models.CharField(default="", max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="korea_stock.stockcodemodel",
                    ),
                ),
            ],
        ),
    ]
