# Generated by Django 5.0.2 on 2024-02-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockCodeModel",
            fields=[
                ("standard_code", models.CharField(default="", max_length=50)),
                (
                    "code",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("stock_name", models.CharField(default="", max_length=100)),
                ("en_name", models.CharField(default="", max_length=100)),
                ("stock_open_date", models.DateField()),
                ("market", models.CharField(default="", max_length=50)),
                ("stock_kind", models.CharField(default="", max_length=10)),
                ("affiliated", models.CharField(default="", max_length=20)),
                ("stock_type", models.CharField(default="", max_length=20)),
                ("face_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_stock_count",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockPriceRealtimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"abstract": False,},
        ),
    ]
