# Generated by Django 5.0.2 on 2024-02-19 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("korea_stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KisSectorModel",
            fields=[
                (
                    "sector_code",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("sector_name", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="KSICCodeModel",
            fields=[
                ("theme_code", models.CharField(default="", max_length=50)),
                ("theme_name", models.CharField(default="", max_length=200)),
                (
                    "ksic_code",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stockinfomodel",
            name="sstd_idst_clsf_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="korea_stock.ksiccodemodel",
            ),
        ),
    ]
