# Generated by Django 5.0.2 on 2024-02-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("korea_stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockcodemodel",
            name="affiliated",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="stockcodemodel",
            name="stock_kind",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="stockcodemodel",
            name="stock_type",
            field=models.CharField(default="", max_length=30),
        ),
    ]
