# Generated by Django 5.0.2 on 2024-02-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("korea_stock", "0002_alter_ksiccodemodel_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockinfomodel",
            old_name="kosdap_mket_lstg_abol_dt",
            new_name="kosdaq_mket_lstg_abol_dt",
        ),
        migrations.RenameField(
            model_name="stockinfomodel",
            old_name="kosdap_mket_lstg_dt",
            new_name="kosdaq_mket_lstg_dt",
        ),
    ]
