# Generated by Django 5.0.2 on 2024-02-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "korea_stock",
            "0003_rename_kosdap_mket_lstg_abol_dt_stockinfomodel_kosdaq_mket_lstg_abol_dt_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockinfomodel",
            old_name="oilf_find_yn",
            new_name="oilf_fund_yn",
        ),
    ]
