# Generated by Django 5.0.2 on 2024-02-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("korea_stock", "0004_rename_oilf_find_yn_stockinfomodel_oilf_fund_yn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockinfomodel",
            old_name="admin_item_yn",
            new_name="admn_item_yn",
        ),
    ]
