# Generated by Django 5.0.2 on 2024-02-25 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("korea_stock", "0005_rename_admin_item_yn_stockinfomodel_admn_item_yn"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("D", "Daily"),
                            ("W", "Weekly"),
                            ("M", "Monthly"),
                            ("Y", "Yearly"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("volume", models.BigIntegerField()),
                (
                    "accumulate_money",
                    models.DecimalField(decimal_places=2, max_digits=30),
                ),
                ("flng_cls_code", models.CharField(default="", max_length=30)),
                ("prtt_rate", models.CharField(default="", max_length=30)),
                ("mod_yn", models.CharField(default="", max_length=30)),
                ("prdy_vrss_sign", models.CharField(default="", max_length=30)),
                ("prdy_vrss", models.CharField(default="", max_length=30)),
                ("revl_issu_reas", models.CharField(default="", max_length=30)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="korea_stock.stockcodemodel",
                    ),
                ),
            ],
        ),
    ]
